spring:
  application.name: seor
  threads:
    virtual:
      enabled: true

server:
  port: 8080

  logging:
    level:
      com.tsm.ur.card.seor.advice: { $LOG_LEVEL:INFO }
    pattern.level: '%5p [traceId=%X{tracingId}]'

wiam:
  base-url: http://localhost:8081
  timeout: 30000

