spring:
  application.name: seor
  threads:
    virtual:
      enabled: true
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:9001
          jwk-set-uri: http://localhost:9001/oauth2/jwks

server:
  port: 8080

  logging:
    level:
      com.tsm.ur.card.seor.advice: { $LOG_LEVEL:INFO }
    pattern.level: '%5p [traceId=%X{tracingId}]'

wiam:
  base-url: http://localhost:8081
  timeout: 30000

